### ISSUE TITLE
onion-setup-build.py is still python2

### ISSUE THREAD

**Issue by misl6** [OnionIoT/source#20]
`python2` is officially dead, but python scripts in this repo are still for `python2`.

Can We move to `python3` ASAP?

**Comment by stefan-golinschi** [comment]
Just made a PR today that also addresses your issue. Check it out here: [PR21](https://github.com/OnionIoT/source/pull/21)

**Comment by LinusU** [comment]
This was fixed by #21, which was just merged

**Comment by greenbreakfast** [comment]
Yep, #21 has been merged. Closing this issue, feel free to reopen if you find any other Python3 incompatible scripts
