### ISSUE TITLE
Missing tags in this repo

### ISSUE THREAD

**Issue by SaschaMzH** [OnionIoT/source#25]
Hi,

I have seen that the current release of the firmware is **0.3.2**. But there is no tag of that version. The latest tag is **0.2.2**.
I think you are still working with that repo, because you are updating the [changelog](https://github.com/OnionIoT/source/blob/openwrt-18.06/CHANGELOG.md) file.

Did you missed to publish the tags as well?

**Comment by greenbreakfast** [comment]
@SaschaMzH yeah, that's right, we're tracking changes in the changelog file and have not published the tags in a while.
Would having tags be helpful? If so, how?

**Comment by SaschaMzH** [comment]
Hi @greenbreakfast,

Yes, tags will be helpfull to see which commit is the current released commit. We use the the onion on a human controlled robot (HuCon) project. This project will help kids to learn a programming language and we need the tags to define our image (we need some packages which are not includes on the base).
Based on your question (how), I think you work on a forked repo. If you do so, you can push your tags on this repo too.

**Comment by greenbreakfast** [comment]
Updated tags to include tags for all v0.3.x releases as well as latest v0.3.3 b256 version
