### ISSUE TITLE
Where is Dockerfile for onion/omega2-source?

### ISSUE THREAD

**Issue by chmorgan** [OnionIoT/source#28]
Hey @greenbreakfast, I'm updating some software that I build to target openwrt using a docker container built upon omega2-source.

What I'm looking to do is upgrade the base container from ubuntu 18.04 to 20.04 so I can get newer versions of node that the latest npm packages depend on.

I can't find the Dockerfile that generates this onion/omega2-source container, if I had this I could help out with the upgrade to this package.

I did also notice a owrt-sdk image but maybe this is for a difference audience?

Oh, and there are a handful of much older images like lede and omega2-toolchain that are 4 years old. Maybe these should be removed if they were supplanted by another newer image?

**Comment by greenbreakfast** [comment]
Hey @chmorgan, the Dockerfile for the [onion/omega2-source docker image](https://hub.docker.com/repository/docker/onion/omega2-source) is in this repo: https://github.com/OnionIoT/source/blob/openwrt-18.06/Dockerfile

We haven't had any strong feedback on the onion/omega2-source docker image, so we haven't set up automatic updates of the image. What are your thoughts on this?

The other docker images on Onion's docker hub are a mixed bag of things we use for CI/CD and experiments. You can safely ignore them.

**Comment by chmorgan** [comment]
@greenbreakfast thanks for the reminder on that. I'm sure I knew where to find that, I was looking at the 21.02 branch!
