### ISSUE TITLE
Where did you define /dev/ttySx

### ISSUE THREAD

**Issue by eyithings** [OnionIoT/source#36]
This is a question I want to direct to Onion.

Where in your build system did you customise (makefile/config/source code) for the Omega2S+ UARTs to show up as a `/dev/ttySx` interface? I am working with drivers and want to modify the source such that `/dev/ttyS1` is not visible from userspace but appears as `/dev/<custom_name>`.

If I am asking the wrong question, kindly point me towards what I need to look at.

Thank you.

**Comment by greenbreakfast** [comment]
I believe this is configured in the DTS files for this device. See:
* https://github.com/OnionIoT/source/blob/openwrt-18.06/target/linux/ramips/dts/mt7628an.dtsi
* https://github.com/OnionIoT/source/blob/openwrt-18.06/target/linux/ramips/dts/OMEGA2.dtsi

But I'm believe changing the name in userspace would require making changes to the kernel. I'm not sure though - your best bet would be to ask people familiar with the kernel.
